const moment  = require("moment");

module.exports = Object.freeze({
    CALENDAR_INITIAL_EVENTS : [
        {title : "Product call", theme : "GREEN", startTime : moment().add(-12, 'd').startOf('day'), endTime : moment().add(-12, 'd').endOf('day')},
        {title : "Meeting with tech team", theme : "PINK", startTime : moment().add(-8, 'd').startOf('day'), endTime : moment().add(-8, 'd').endOf('day')},
        {title : "Meeting with Cristina", theme : "PURPLE", startTime : moment().add(-2, 'd').startOf('day'), endTime : moment().add(-2, 'd').endOf('day')},
        {title : "Meeting with Alex", theme : "BLUE", startTime : moment().startOf('day'), endTime : moment().endOf('day')}, 
        {title : "Product Call", theme : "GREEN", startTime : moment().startOf('day'), endTime : moment().endOf('day')},
        {title : "Client Meeting", theme : "PURPLE", startTime : moment().startOf('day'), endTime : moment().endOf('day')},
        {title : "Client Meeting", theme : "ORANGE", startTime : moment().add(3, 'd').startOf('day'), endTime : moment().add(3, 'd').endOf('day')},
        {title : "Product meeting", theme : "PINK", startTime : moment().add(5, 'd').startOf('day'), endTime : moment().add(5, 'd').endOf('day')},
        {title : "Sales Meeting", theme : "GREEN", startTime : moment().add(8, 'd').startOf('day'), endTime : moment().add(8, 'd').endOf('day')},
        {title : "Product Meeting", theme : "ORANGE", startTime : moment().add(8, 'd').startOf('day'), endTime : moment().add(8, 'd').endOf('day')},
        {title : "Marketing Meeting", theme : "PINK", startTime : moment().add(8, 'd').startOf('day'), endTime : moment().add(8, 'd').endOf('day')},
        {title : "Client Meeting", theme : "GREEN", startTime : moment().add(8, 'd').startOf('day'), endTime : moment().add(8, 'd').endOf('day')},
        {title : "Sales meeting", theme : "BLUE", startTime : moment().add(12, 'd').startOf('day'), endTime : moment().add(12, 'd').endOf('day')},
        {title : "Client meeting", theme : "PURPLE", startTime : moment().add(16, 'd').startOf('day'), endTime : moment().add(16, 'd').endOf('day')},
    ],

    SUMMARY: {
        "totalQuantity": 1546,
        "totalAmount": 313388,
        "totalNetAmount": 301847.02,
        "totalAverageAmount": 202.71,
        "initialDate": "2021-05-26",
        "finalDate": "2021-05-26"
    },

    RECENT_TRANSACTIONS : [
        {name : "Alex", avatar : "https://reqres.in/img/faces/1-image.jpg", email : "alex@dashwind.com", location : "Paris", amount : 100, date : moment().endOf('day')},
        {name : "Ereena", avatar : "https://reqres.in/img/faces/2-image.jpg", email : "ereena@dashwind.com", location : "London", amount : 190, date : moment().add(-1, 'd').endOf('day')},
        {name : "John", avatar : "https://reqres.in/img/faces/3-image.jpg", email : "jhon@dashwind.com", location : "Canada", amount : 112, date : moment().add(-1, 'd').endOf('day')},
        {name : "Matrix", avatar : "https://reqres.in/img/faces/4-image.jpg", email : "matrix@dashwind.com", location : "Peru", amount : 111, date : moment().add(-1, 'd').endOf('day')},
        {name : "Virat", avatar : "https://reqres.in/img/faces/5-image.jpg", email : "virat@dashwind.com", location : "London", amount : 190, date : moment().add(-2, 'd').endOf('day')},
        {name : "Miya", avatar : "https://reqres.in/img/faces/6-image.jpg", email : "miya@dashwind.com", location : "Paris", amount : 230, date : moment().add(-2, 'd').endOf('day')},
        {name : "Virat", avatar : "https://reqres.in/img/faces/3-image.jpg", email : "virat@dashwind.com", location : "Canada", amount : 331, date : moment().add(-2, 'd').endOf('day')},
        {name : "Matrix", avatar : "https://reqres.in/img/faces/1-image.jpg", email : "matrix@dashwind.com", location : "London", amount : 581, date : moment().add(-2, 'd').endOf('day')},
        {name : "Ereena", avatar : "https://reqres.in/img/faces/3-image.jpg", email : "ereena@dashwind.com", location : "Tokyo", amount : 151, date : moment().add(-2, 'd').endOf('day')},
        {name : "John", avatar : "https://reqres.in/img/faces/2-image.jpg", email : "jhon@dashwind.com", location : "Paris", amount : 91, date : moment().add(-2, 'd').endOf('day')},
        {name : "Virat", avatar : "https://reqres.in/img/faces/3-image.jpg", email : "virat@dashwind.com", location : "Canada", amount : 161, date : moment().add(-3, 'd').endOf('day')},
        {name : "Matrix", avatar : "https://reqres.in/img/faces/4-image.jpg", email : "matrix@dashwind.com", location : "US", amount : 121, date : moment().add(-3, 'd').endOf('day')},
        {name : "Ereena", avatar : "https://reqres.in/img/faces/6-image.jpg", email : "jhon@dashwind.com", location : "Tokyo", amount : 713, date : moment().add(-3, 'd').endOf('day')},
        {name : "John", avatar : "https://reqres.in/img/faces/2-image.jpg", email : "ereena@dashwind.com", location : "London", amount : 217, date : moment().add(-3, 'd').endOf('day')},
        {name : "Virat", avatar : "https://reqres.in/img/faces/3-image.jpg", email : "virat@dashwind.com", location : "Paris", amount : 117, date : moment().add(-3, 'd').endOf('day')},
        {name : "Miya", avatar : "https://reqres.in/img/faces/7-image.jpg", email : "jhon@dashwind.com", location : "Canada", amount : 612, date : moment().add(-3, 'd').endOf('day')},
        {name : "Matrix", avatar : "https://reqres.in/img/faces/3-image.jpg", email : "matrix@dashwind.com", location : "London", amount : 631, date : moment().add(-3, 'd').endOf('day')},
        {name : "Virat", avatar : "https://reqres.in/img/faces/2-image.jpg", email : "ereena@dashwind.com", location : "Tokyo", amount : 151, date : moment().add(-3, 'd').endOf('day')},
        {name : "Ereena", avatar : "https://reqres.in/img/faces/3-image.jpg", email : "virat@dashwind.com", location : "Paris", amount : 617, date : moment().add(-3, 'd').endOf('day')},
    ],

    TRANSACTIONS : [
        {
          "id": "114606514478703",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Mastercard",
          "authorizationCode": "378216",
          "truncatedCardNumber": "1014",
          "grossAmount": 80,
          "netAmount": 76.88,
          "terminal": "00032668",
          "administrationFee": 3.9,
          "channelCode": 15,
          "channel": "Super Link / Digitada",
          "withdrawAmount": 0,
          "minimumMDRAmmount": -3.12,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -3.12,
          "status": "Aprovada"
        },
        {
          "id": "114606514478704",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Mastercard",
          "authorizationCode": "378218",
          "truncatedCardNumber": "1014",
          "grossAmount": 80,
          "netAmount": 76.88,
          "terminal": "00032668",
          "administrationFee": 3.9,
          "channelCode": 15,
          "channel": "Super Link / Digitada",
          "withdrawAmount": 0,
          "minimumMDRAmmount": -3.12,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -3.12,
          "status": "Aprovada"
        },
        {
          "id": "114606514478705",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Mastercard",
          "authorizationCode": "378224",
          "truncatedCardNumber": "1014",
          "grossAmount": 90,
          "netAmount": 86.49,
          "terminal": "00032668",
          "administrationFee": 3.9,
          "channelCode": 15,
          "channel": "Super Link / Digitada",
          "withdrawAmount": 0,
          "minimumMDRAmmount": -3.51,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -3.51,
          "status": "Aprovada"
        },
        {
          "id": "114606514478706",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Mastercard",
          "authorizationCode": "378226",
          "truncatedCardNumber": "1014",
          "grossAmount": 90,
          "netAmount": 86.49,
          "terminal": "00032668",
          "administrationFee": 3.9,
          "channelCode": 15,
          "channel": "Super Link / Digitada",
          "withdrawAmount": 0,
          "minimumMDRAmmount": -3.51,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -3.51,
          "status": "Aprovada"
        },
        {
          "id": "114606514478701",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Mastercard",
          "authorizationCode": "378204",
          "truncatedCardNumber": "1014",
          "grossAmount": 70,
          "netAmount": 67.27,
          "terminal": "32668",
          "administrationFee": 3.9,
          "channelCode": 1,
          "channel": "Máquina",
          "withdrawAmount": 0,
          "minimumMDRAmmount": 0,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -2.73,
          "status": "Aprovada"
        },
        {
          "id": "114606514478705",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Mastercard",
          "authorizationCode": "378224",
          "truncatedCardNumber": "1014",
          "grossAmount": 90,
          "netAmount": 86.49,
          "terminal": "32668",
          "administrationFee": 3.9,
          "channelCode": 1,
          "channel": "Máquina",
          "withdrawAmount": 0,
          "minimumMDRAmmount": 0,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -3.51,
          "status": "Aprovada"
        },
        {
          "id": "114606514478366",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Mastercard",
          "authorizationCode": "339150",
          "truncatedCardNumber": "1014",
          "grossAmount": 90,
          "netAmount": 86.49,
          "terminal": "32668",
          "administrationFee": 3.9,
          "channelCode": 1,
          "channel": "Máquina",
          "withdrawAmount": 0,
          "minimumMDRAmmount": 0,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -3.51,
          "status": "Aprovada"
        },
        {
          "id": "114606514478688",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Elo",
          "authorizationCode": "378142",
          "truncatedCardNumber": "1014",
          "grossAmount": 70,
          "netAmount": 67.27,
          "terminal": "32668000",
          "administrationFee": 3.9,
          "channelCode": 1,
          "channel": "Máquina",
          "withdrawAmount": 0,
          "minimumMDRAmmount": 0,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -2.73,
          "status": "Aprovada"
        },
        {
          "id": "114606514478686",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Mastercard",
          "authorizationCode": "378134",
          "truncatedCardNumber": "1014",
          "grossAmount": 600,
          "netAmount": 570.66,
          "terminal": "32668000",
          "administrationFee": 3.9,
          "channelCode": 1,
          "channel": "Máquina",
          "withdrawAmount": 0,
          "minimumMDRAmmount": 0,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -20.34,
          "status": "Aprovada"
        },
        {
          "id": "114606514478685",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Elo",
          "authorizationCode": "378132",
          "truncatedCardNumber": "1014",
          "grossAmount": 60,
          "netAmount": 57.66,
          "terminal": "32668000",
          "administrationFee": 3.9,
          "channelCode": 1,
          "channel": "Máquina",
          "withdrawAmount": 0,
          "minimumMDRAmmount": 0,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -2.34,
          "status": "Aprovada"
        },
        {
          "id": "114606514478684",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Mastercard",
          "authorizationCode": "378126",
          "truncatedCardNumber": "1014",
          "grossAmount": 50,
          "netAmount": 48.05,
          "terminal": "32668000",
          "administrationFee": 3.9,
          "channelCode": 1,
          "channel": "Máquina",
          "withdrawAmount": 0,
          "minimumMDRAmmount": 0,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -1.95,
          "status": "Aprovada"
        },
        {
          "id": "114606514478703",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Elo",
          "authorizationCode": "378216",
          "truncatedCardNumber": "1014",
          "grossAmount": 80,
          "netAmount": 76.88,
          "terminal": "32668",
          "administrationFee": 3.9,
          "channelCode": 1,
          "channel": "Máquina",
          "withdrawAmount": 0,
          "minimumMDRAmmount": 0,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -3.12,
          "status": "Aprovada"
        },
        {
          "id": "114606514478704",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Mastercard",
          "authorizationCode": "378218",
          "truncatedCardNumber": "1014",
          "grossAmount": 80,
          "netAmount": 76.88,
          "terminal": "32668",
          "administrationFee": 3.9,
          "channelCode": 1,
          "channel": "Máquina",
          "withdrawAmount": 0,
          "minimumMDRAmmount": 0,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -3.12,
          "status": "Aprovada"
        },
        {
          "id": "114606514478702",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Mastercard",
          "authorizationCode": "378206",
          "truncatedCardNumber": "1014",
          "grossAmount": 70,
          "netAmount": 67.27,
          "terminal": "32668",
          "administrationFee": 3.9,
          "channelCode": 1,
          "channel": "Máquina",
          "withdrawAmount": 0,
          "minimumMDRAmmount": 0,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -2.73,
          "status": "Aprovada"
        },
        {
          "id": "114606514478356",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Mastercard",
          "authorizationCode": "339130",
          "truncatedCardNumber": "1014",
          "grossAmount": 70,
          "netAmount": 67.27,
          "terminal": "32668000",
          "administrationFee": 3.9,
          "channelCode": 3,
          "channel": "Ecommerce",
          "withdrawAmount": 0,
          "minimumMDRAmmount": 0,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -2.73,
          "status": "Aprovada"
        },
        {
          "id": "114606514478693",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Visa",
          "authorizationCode": "378164",
          "truncatedCardNumber": "7972",
          "grossAmount": 74,
          "netAmount": 71.11,
          "terminal": "32668",
          "administrationFee": 3.9,
          "channelCode": 3,
          "channel": "Ecommerce",
          "withdrawAmount": 0,
          "minimumMDRAmmount": 0,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -2.89,
          "status": "Aprovada"
        },
        {
          "id": "114606514478692",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Visa",
          "authorizationCode": "378154",
          "truncatedCardNumber": "7972",
          "grossAmount": 64,
          "netAmount": 61.5,
          "terminal": "32668",
          "administrationFee": 3.9,
          "channelCode": 1,
          "channel": "Máquina",
          "withdrawAmount": 0,
          "minimumMDRAmmount": 0,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -2.5,
          "status": "Pendente"
        },
        {
          "id": "114606514478357",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Visa",
          "authorizationCode": "339132",
          "truncatedCardNumber": "7972",
          "grossAmount": 54,
          "netAmount": 51.89,
          "terminal": "32668",
          "administrationFee": 3.9,
          "channelCode": 1,
          "channel": "Máquina",
          "withdrawAmount": 0,
          "minimumMDRAmmount": 0,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -2.11,
          "status": "Aprovada"
        },
        {
          "id": "114606514478691",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Visa",
          "authorizationCode": "378152",
          "truncatedCardNumber": "7972",
          "grossAmount": 64,
          "netAmount": 61.5,
          "terminal": "32668",
          "administrationFee": 3.9,
          "channelCode": 1,
          "channel": "Máquina",
          "withdrawAmount": 0,
          "minimumMDRAmmount": 0,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -2.5,
          "status": "Aprovada"
        },
        {
          "id": "114606514478690",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Hipercard",
          "authorizationCode": "378146",
          "truncatedCardNumber": "7972",
          "grossAmount": 54,
          "netAmount": 51.89,
          "terminal": "32668",
          "administrationFee": 3.9,
          "channelCode": 1,
          "channel": "Máquina",
          "withdrawAmount": 0,
          "minimumMDRAmmount": 0,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -2.11,
          "status": "Pendente"
        },
        {
          "id": "114606514478357",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Visa",
          "authorizationCode": "339132",
          "truncatedCardNumber": "7972",
          "grossAmount": 54,
          "netAmount": 51.89,
          "terminal": "00032668",
          "administrationFee": 3.9,
          "channelCode": 1,
          "channel": "Máquina",
          "withdrawAmount": 0,
          "minimumMDRAmmount": -2.11,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -2.11,
          "status": "Aprovada"
        },
        {
          "id": "114606514478358",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Visa",
          "authorizationCode": "339134",
          "truncatedCardNumber": "7972",
          "grossAmount": 64,
          "netAmount": 61.5,
          "terminal": "00032668",
          "administrationFee": 3.9,
          "channelCode": 1,
          "channel": "Máquina",
          "withdrawAmount": 0,
          "minimumMDRAmmount": -2.5,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -2.5,
          "status": "Aprovada"
        },
        {
          "id": "114606514478359",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Visa",
          "authorizationCode": "339136",
          "truncatedCardNumber": "7972",
          "grossAmount": 74,
          "netAmount": 71.11,
          "terminal": "00032668",
          "administrationFee": 3.9,
          "channelCode": 1,
          "channel": "Máquina",
          "withdrawAmount": 0,
          "minimumMDRAmmount": -2.89,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -2.89,
          "status": "Negada"
        },
        {
          "id": "114606514478689",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Elo",
          "authorizationCode": "378144",
          "truncatedCardNumber": "7972",
          "grossAmount": 54,
          "netAmount": 51.89,
          "terminal": "00032668",
          "administrationFee": 3.9,
          "channelCode": 1,
          "channel": "Máquina",
          "withdrawAmount": 0,
          "minimumMDRAmmount": -2.11,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -2.11,
          "status": "Aprovada"
        },
        {
          "id": "114606514478690",
          "merchantId": "2000463023",
          "paymentNode": 485173,
          "cnpjRoot": 485116,
          "date": "2021-05-26T12:12:55",
          "paymentType": "Crédito à vista",
          "cardBrand": "Visa",
          "authorizationCode": "378146",
          "truncatedCardNumber": "7972",
          "grossAmount": 5400,
          "netAmount": 5100.89,
          "terminal": "00032668",
          "administrationFee": 3.9,
          "channelCode": 1,
          "channel": "Máquina",
          "withdrawAmount": 0,
          "minimumMDRAmmount": -200.11,
          "mdrTaxAmount": 0,
          "mdrFeeAmount": -200.11,
          "status": "Aprovada"
        }
      ]
});
